# Generated by Django 3.2.12 on 2022-03-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.SmallIntegerField(blank=True, null=True, verbose_name='人数')),
                ('title', models.TextField(blank=True, max_length=64, null=True, verbose_name='课题')),
                ('url', models.CharField(blank=True, max_length=128, null=True, verbose_name='课程链接')),
                ('mark', models.SmallIntegerField(blank=True, null=True, verbose_name='评分')),
                ('text_data', models.TextField(blank=True, max_length=10000, null=True, verbose_name='课程内容')),
            ],
        ),
    ]
