# Generated by Django 3.2.12 on 2022-03-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKapp01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_data',
            name='rank',
            field=models.FloatField(blank=True, null=True, verbose_name='人数'),
        ),
    ]
