# Generated by Django 3.2.12 on 2022-03-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKapp01', '0002_alter_c_data_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_data',
            name='rank',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='人数'),
        ),
    ]
