# Generated by Django 3.2.12 on 2022-03-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKapp01', '0003_alter_c_data_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_data',
            name='mark',
            field=models.FloatField(blank=True, null=True, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='c_data',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='人数'),
        ),
    ]
