# Generated by Django 3.2.12 on 2022-03-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKapp01', '0004_auto_20220331_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c_data',
            name='rank',
        ),
        migrations.AddField(
            model_name='c_data',
            name='people',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='人数'),
        ),
    ]
